### ISSUE TITLE
Auto redirect to the Telegram channel when entering the admin panel

### ISSUE THREAD

**Issue by emomaliev** [OkayCMS/Okay#24]
When you enter the admin panel, it opens a third-party link without permission, not allowing you to open the admin panel.
----
want to say that this is very mean. We ordinary users are not to blame and do not influence the politics of our countries. Why do regular users have to deal with this? Why are open-source projects increasingly becoming political levers?

**Comment by OkayCMS** [comment]
If our product allows a company to work better and earn more, that company pays more taxes. With these taxes, Russia makes rockets and bombs that are exploding in my city right now. I do not want to finance the bombing of my city and my country, even in this way, so I forbid our product from being used in Russia.

**Comment by sergannn** [comment]
> ## When you enter the admin panel, it opens a third-party link without permission, not allowing you to open the admin panel.
> I want to say that this is very mean. We ordinary users are not to blame and do not influence the politics of our countries. Why do regular users have to deal with this? Why are open-source projects increasingly becoming political levers? What about those who do not share what is happening now? Suffer too?

just switch off google tag manager
